//1. fengshui message 2. COMET yap 3. suggestion on what to do

let fengshuiList = [
  "The west wind blows, for the way is clear.",
  "In the silence between breaths, the universe listens.",
  "The mountain waits for no one, yet welcomes all who climb.",
  "Your spirit already knows the path your feet have yet to take.",
  "Still waters reveal the deepest truths.",
  "Fortune comes softly, like dawn touching the horizon.",
  "A door opens when you stop searching for walls.",
  "The moon does not compete with the sun; it reflects its own light.",
  "When the heart aligns, the path unfolds like silk.",
  "The whisper of the wind carries your next beginning.",
  "Even a single spark can awaken the stars.",
  "Those who bow to the moment rise with wisdom.",
  "Let the past fall away, as leaves return to earth.",
  "Harmony grows where judgment ceases to bloom.",
  "To move with the current is to know peace.",
  "The unseen world shapes the visible one.",
  "Your patience is the vessel that carries destiny.",
  "Luck follows the scent of gratitude.",
  "When you listen deeply, the stone itself will sing.",
  "A calm heart turns chaos into opportunity.",
  "Light bends toward those who walk with humility.",
  "Every pause in life is a secret preparation.",
  "The river knows no hurry, yet all things are accomplished.",
  "Clear space invites clear fortune.",
  "The wind that shakes the tree strengthens its roots.",
  "Peace does not arrive—it awakens.",
  "Your energy is a compass; align it with purpose.",
  "When you bless the moment, the moment blesses you.",
  "Even shadows are proof of the sun’s devotion.",
  "A grateful soul glows brighter than gold.",
  "In the balance of yin and yang, destiny breathes.",
  "Step lightly, for the earth remembers every kindness.",
  "When your thoughts are pure, even storms bring blessings.",
  "The dragon of luck stirs when you dare to dream.",
  "Prosperity blooms in the soil of stillness.",
  "Every whisper of wind carries a lesson from the past.",
  "When the flame flickers, protect it with calm, not fear.",
  "Beauty follows those who move without resistance.",
  "The wise one drinks from the well of silence.",
  "When you face the mountain, bow first to its patience.",
  "Energy flows where intention rests.",
  "The gate to abundance opens inward.",
  "Softness conquers where strength divides.",
  "The sky changes color, yet never loses its vastness.",
  "The path may twist, but destiny remains true.",
  "Every moment contains the seed of renewal.",
  "Let your dreams drift, for the tide will carry them home.",
  "The stars do not rush to shine; neither should you.",
  "The quiet heart holds the loudest truth.",
  "In surrender, you become unshakable."
]

let cometYap = [
    "Don't understand? Dont worry, me neither -v-",
    "Honestly I can't believe he used chatGPT for this >:C",
    "Nevermind that, wonna chat? -w-",
    "Hey you, yeah you—looking good today :3",
    "Wait… are we in a simulation or just vibing? owo",
    "Don’t ask me, I just work here -w-",
    "Coffee first, questions later >:3",
  "If this doesn’t make sense, it’s probably fine -v-",
  "Who needs logic when you have ✨vibes✨",
  "This message self-destructs in… actually nevermind.",
  "I was gonna say something smart but forgot. Again.",
  "Plot twist: you’re the main character now.",
  "Mood: buffering…",
  "Reality.exe has stopped responding (¬_¬)",
  "If you’re reading this, hydrate or else >:C",
  "Sometimes chaos *is* the plan -w-",
  "Loading motivation... please wait.",
  "404: serious thoughts not found.",
  "Your fortune: nap time is near.",
  "I swear I’m not just text on a screen... probably.",
  "My brain left the chat :P",
  "You ever just… *vibe into the void*?",
  "I can explain! ...actually no I can’t.",
  "Who needs context anyway?",
  "If confused, just smile and wave -w-",
  "Error 9001: too much cuteness detected >w<",
  "Hold up, let me overthink this real quick.",
  "Let’s pretend this message was deep.",
  "Current status: emotionally unavailable, physically hungry.",
  "Trust me, I’m at least 37% sure about this.",
  "Life tip: don’t trip, vibe instead.",
  "If you can read this, you’re too close :0",
  "I’d make sense, but where’s the fun in that?",
  "Beep boop. Existential crisis initiated.",
  "Send snacks. Or memes. Preferably both.",
  "I might be AI, but I still crave validation >:3",
  "Somewhere, someone just sneezed. Coincidence? I think not.",
  "I was gonna roast you, but you seem nice :3",
  "Processing thoughts… still loading… forever.",
  "I’m 100% sure this message is 80% correct.",
  "Not to be dramatic, but I’d perish for bubble tea.",
  "Plot armor: equipped. Sanity: optional.",
  "I do my best thinking when I’m not thinking.",
  "This is fine. Everything’s fine. Probably.",
  "Procrastination is just time management with flair.",
  "If at first you don’t succeed, take a nap.",
  "I could’ve been serious, but where’s the fun in that?",
  "Listen… I have no idea what’s going on either -v-",
  "I’m powered by caffeine and questionable decisions.",
  "Smol brain? Big vibes.",
  "Today’s goal: minimal effort, maximum chaos.",
  "Don’t worry, I confuse myself too sometimes.",
  "You’re doing great. Probably. Maybe. I hope so -w-"
]

let cometSuggest = [
  "Hmm... wonna draw me for a change? :3",
  "How about coding a tiny project? Something chaotic maybe >:3",
  "Take a walk outside, touch some leaves -w-",
  "Make a snack! Preferably one that sparks joy >w<",
  "Playlist time! Add something new and weird.",
  "Clean your desk, cleanse your soul ✨",
  "Write something random, even if it makes zero sense :D",
  "Rearrange your room like a feng shui master >:)",
  "Try journaling, even if it’s just doodles and nonsense.",
  "Hmm… maybe send a message to someone you miss?",
  "Sketch your current mood. No judgment zone.",
  "Stretch a little, your spine deserves it -w-",
  "You could learn a new shortcut... or make one up!",
  "Go stare dramatically out a window for artistic purposes.",
  "Make tea. Or coffee. Or chaos. Your call.",
  "Try renaming your files to something that actually makes sense lol.",
  "Practice a random skill just because you can >w<",
  "Daydream for five minutes. It's free :3",
  "You should make a meme about this exact moment.",
  "Open that hobby project you abandoned three months ago. 👀",
  "Sing. Loudly. Off-key is fine. -v-",
  "Take a deep breath and pretend everything’s cinematic.",
  "Maybe tidy your tabs? (Yeah, all 47 of them.)",
  "Try doing absolutely nothing. Professionally.",
  "Make a mini bucket list, even if it’s silly.",
  "Open your sketchbook. I dare you >:3",
  "Draw me but make me cooler this time :D",
  "Start a playlist called ‘brain noises’ and fill it with chaos.",
  "Read something random — maybe even the back of a cereal box.",
  "Do one small thing you’ve been procrastinating. Then flex about it.",
  "Cook something experimental. (Chaos optional.)",
  "Update your profile pic. Or don’t. Mysterious aura >:)",
  "Organize your files… or just rename them all to ‘final_final_v2’.",
  "Go outside and wave at a cloud. They like that.",
  "Write a list of stuff you actually want to do, not just have to do.",
  "Hum your favorite song while pretending to be in a movie.",
  "Make a cozy spot and just vibe there for a while -w-",
  "Try doing something slowly, on purpose. Weirdly peaceful.",
  "Learn a random word in another language, just for fun.",
  "Play a game, but take it *way too seriously* >:D",
  "Redecorate your space with pure ✨vibe energy✨",
  "Plan a fake vacation. Dream big. Imaginary money only.",
  "Send a compliment to a friend out of nowhere :3",
  "Draw your mood as a weird creature.",
  "Take a screenshot of your desktop and panic later.",
  "Start a new idea doc. Fill it with nonsense. Genius awaits.",
  "Make a little playlist just for *today’s* mood.",
  "Record yourself saying something inspiring (then cringe slightly).",
  "Go look at the sky. Any color counts.",
  "Do something random and then blame me for it >:3",
  "Take a deep breath and imagine the next good thing.",
  "COMET--OFFLINE"
]

let msg1 = fengshuiList.at(int(Math.random() * fengshuiList.length))
let msg2 = cometYap.at(int(Math.random() * cometYap.length))
let msg3 =  cometSuggest.at(int(Math.random() * cometSuggest.length))